### ISSUE TITLE
Show diff output?

### ISSUE THREAD

**Issue by dsully** [Chaitanyabsprip/fastaction.nvim#1]
Any plans to show diff output for actions that support it?

Thanks

**Comment by Chaitanyabsprip** [comment]
I'm aware of another plugin that already does this, however it's a telescope/fzf like picker where a preview fits well. However in this plugin, there is no way to "browse" the options, you're just presented with options and you choose one. I can't think of a way where a diff output/preview would fit in this workflow. If you have any ideas, do share.

**Comment by Chaitanyabsprip** [comment]
If you have any suggestions, please reopen with a comment. Meanwhile I'll close this issue. Thanks.
