### ISSUE TITLE
Feature request: fall back to `vim.ui.select` if code action list is too long

### ISSUE THREAD

**Issue by mawkler** [Chaitanyabsprip/fastaction.nvim#10]
Thanks for making this awesome plugin! I've ran into some cases (specifically with rust-analyzer) where the list of available code-actions is too long to actually display them all. Would it be possible to implement a fallback strategy where, if the list supersedes a certain amount (say 30) fastaction simply calls `vim.ui.select` instead, allowing me to search through the list with telescope (using dressing.nvim)?

**Comment by Chaitanyabsprip** [comment]
Thanks for raising this feature request @mawkler. I have thought about this. I have recently added support for >26 options in fastaction. However, now I realize that the size of the window can be a problem in which case it is important to either support scroll or support falling back on either telescope, fzf or vim.ui.select. I'm leaning towards falling back on these external tools as you suggested. I suggest a configuration option in fastaction which will set the threshold after which fastaction will delegate the selection to these plugins or vim.ui.select. What do you think of this approach?

**Comment by mawkler** [comment]
That sounds perfect! Perhaps the simplest and most dogmatic implementation is to only fall back to `vim.ui.select`, and let the user configure `vim.ui.select` to use the picker of their choice, i.e. telescope, fzf, noice, etc. I would say that this is how most other plugins do it.

**Comment by Chaitanyabsprip** [comment]
fixed with 0a908a5

**Comment by mawkler** [comment]
Awesome! Thank you!
