### ISSUE TITLE
Can't get custom keys to work

### ISSUE THREAD

**Issue by mawkler** [Chaitanyabsprip/fastaction.nvim#11]
Hi! I'm trying to set custom keys to use for specific code actions, but can't get them to work.

Here's what my config looks like:

```lua
{
  opts = {
    priority = {
      rust = {
        { pattern = 'Fill match arms', key = 'm', order = 1 },
        { pattern = 'Add `#[derive]`', key = 'd', order = 2 },
      }
    }
  }
}
```

I've tried for more filetypes as well, but can't seem to change the key. Perhaps I'm misunderstanding the point of "priority". I would like for the code action `Fill match arms` to have the key `m`. Should this config achieve that? It keeps getting the key `f`.

**Comment by Chaitanyabsprip** [comment]
```lua
rust = {
   { pattern = 'fill match arms', key = 'm', order = 1 },
   { pattern = 'add `#%[derive%]`', key = 'd', order = 2 },
},
```

This will work. The pattern should be a lua pattern.

**Comment by mawkler** [comment]
Aha the issue seemed to be that I was using an uppercase first letter for the pattern, because that's what the code action has. Perhaps that should be allowed as well, or at least mentioned somewhere because I'm guessing that I won't be the last one to make that mistake? :)

**Comment by Chaitanyabsprip** [comment]
ignore case in pattern since commit 0e3b599

**Comment by mawkler** [comment]
Thank you!
