### ISSUE TITLE
Code actions sometimes time out

### ISSUE THREAD

**Issue by mawkler** [Chaitanyabsprip/fastaction.nvim#12]
Hi! I've noticed that since I started using fastaction.nvim, sometimes when I call `require('fastaction').code_action()` Neovim freezes, and after some time I get the message `ERROR: timeout`. It then spawns a tiny window with the following content:

```
 Code Actions:
─

```

I haven't been able to reliably reproduce this issue because it only happens sometimes. But if I remove fastaction.nvim I never get the behaviour (i.e. I never get any timeouts at all). The freezing seems to be because fastaction.nvim calls `vim.lsp.buf_request_sync` instead of `vim.lsp.buf_request_all`. Do you have any plans to make fastaction.nvim asynchronous?

Do you have any idea what could be causing the timeout? Sorry for not being able to provide a reproducible config.

**Comment by Chaitanyabsprip** [comment]
I have not thought about asynchronous yet, preliminarily it seems to have a few problems. For example cases where the original call site is out of viewport, buffer is closed, window is closed, etc. Will have to think about it, either way, I think the timeout should be configurable. Will look into it.
