### ISSUE TITLE
Feature request: Add a way to center the window

### ISSUE THREAD

**Issue by gustavkrist** [Chaitanyabsprip/fastaction.nvim#13]
I may be missing something, but I was not able to figure out a reliable way to center the popup window. I would prefer to have it pop up in the center of either the editor or the current window, but without knowing the width and height of the window ahead of time, I can't center it using the `x_offset` and `y_offset` parameters. (For `vim.ui.select` usage I can make a wrapper function and do the same calculations to get the width and height as the `fastaction.select` function, but that is also not ideal).

I've made a PR implementing a fix (https://github.com/Chaitanyabsprip/fastaction.nvim/pull/15), I'll happily make any requested changes.

**Comment by Chaitanyabsprip** [comment]
Hey, I've just added two options to configure x and y offset of the popup. This should help you achieve a centered popup window. These will work only when the relative option is set to one of editor, win.
