### ISSUE TITLE
Feature request: allow setting priority based on language server name

### ISSUE THREAD

**Issue by mawkler** [Chaitanyabsprip/fastaction.nvim#16]
Hi! I find the priority handling feature of this plugin super useful for hard-coding the trigger letters for some specific code-actions. However, it's a bummer that I have to specify priority based on the file type because I would like to set a code action for [typos_lsp](https://github.com/tekumara/typos-lsp) which is a language server for typos that is attached to basically all file types.

To me it would make more sense if the key of `priority` were the language server name, rather than the name of the file type. That would solve a bunch of similar problems, for instance [typescript-langauge-server](https://github.com/typescript-language-server/typescript-language-server), which attaches to both JavaScript and TypeScript files (as well as to similar flavours like TypeScriptReact, etc.). That means that the user would have to duplicate their setup for all those variants, even though they all use the same language server.

What do you say?

**Comment by Chaitanyabsprip** [comment]
I am working on this exact functionality, for typos_lsp itself. So stay tuned, I'll make a release soon with this feature. Also thanks for the feature request!

**Comment by Chaitanyabsprip** [comment]
closed with aa7207746
