### ISSUE TITLE
Feature request: configurable position when used as vim.ui.select

### ISSUE THREAD

**Issue by adriankarlen** [Chaitanyabsprip/fastaction.nvim#21]
I'd like to be able to set a specific position for the action menu when used a `vim.ui.select`.

**Comment by Chaitanyabsprip** [comment]
That is already possible using the `popup` table in the configuration table.

**Comment by Chaitanyabsprip** [comment]
see https://github.com/Chaitanyabsprip/fastaction.nvim/blob/24255a74e0d35f1e1807aa78997f5c31ae419dbc/lua/fastaction/types.lua#L56

**Comment by adriankarlen** [comment]
Thank you for your quick reply, this however makes the code action also change position. I do think i phrased my request badly, but the solution to my isuse was to pass `x_offset` like this:
```lua
opts {
  popup {
    x_offset = vim.api.nvim_get_option_value("columns", {}),
  }
}
```

This offsets the window when relative to editor. It would however be nice to separate the relative configuration of the code action and `vim.ui.input`. Closing this as the issue is resolved.
