### ISSUE TITLE
Get "no code actions available" even if code actions are available with `vim.lsp.buf.code_action`

### ISSUE THREAD

**Issue by galou** [Chaitanyabsprip/fastaction.nvim#22]
fastaction doesn't list code actions that `vim.lsp.buf.code_action` proposes.

Config, in lazy: `{'Chaitanyabsprip/fastaction.nvim'},` in `lua/bindings.lua`:
```
local opts = {noremap = true, silent = true}
local fastaction = require('fastaction')
vim.keymap.set('n', '<leader>fa', fastaction.code_action, opts)
vim.keymap.set('v', '<leader>fa', fastaction.range_code_action, opts
```

I get `no code actions available`.

NVIM v0.11.0-dev                                                                                                                                                                               
Build type: RelWithDebInfo                                                                                                                                                                     
LuaJIT 2.1.1703358377

**Comment by kanium3** [comment]
I had the same issue with my Neovim. I don't know if it will be helpful, but I've attached a minimal configuration file.

## Version
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260

## Reproduction 
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
vim.g.mapleader = " " -- leaderkey is <space>

require("lazy.minit").repro({
    spec = {
        {
            "Chaitanyabsprip/fastaction.nvim",
            opts = {},
        },
        {
            "neovim/nvim-lspconfig",
            config = function()
                -- Some Language Server Settings
                -- As an example, luals
                require("lspconfig").lua_ls.setup({
                    cmd = { "<the path of lua-language-server>" }
                })
                local opts = { noremap = true, silent = true }
                local fastaction = require("fastaction")
                vim.keymap.set("n", "<leader>fa", fastaction.code_action, opts)
                vim.keymap.set("v", "<leader>fa", fastaction.range_code_action, opts)
            end,
        },
    },
})
```

**Comment by Chaitanyabsprip** [comment]
I was expecting a minimal project where you had this discrepancy between fastaction and vim.lsp.buf.code_actions. I tried reproducing this case in my other repositories, haven't found anything yet.

As a point of clarification, are you getting >20 code actions?

**Comment by galou** [comment]
Sorry, this example is only minimal if you already have `clangd` installed but I didn't manage to have it work with `lua_ls`.

`init.lua`:
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
            "Chaitanyabsprip/fastaction.nvim",
            opts = {},
        },
        {
            "neovim/nvim-lspconfig",
            config = function()
                -- Some Language Server Settings
                -- As an example, luals
                require("lspconfig").clangd.setup({
                    --cmd = {vim.fn.expand("~/.local/share/nvim/mason/bin/clangd") }
                })
                local opts = { noremap = true, silent = true }
                local fastaction = require("fastaction")
                vim.keymap.set("n", "<leader>fa", fastaction.code_action, opts)
                vim.keymap.set("v", "<leader>fa", fastaction.range_code_action, opts)
            end,
        },
    },
})
```

`main.cpp`:
```cpp
#include <iostream>

int main(int, char**)
{
}
```

Install `clangd`.

`vim -u init.lua main.cpp`, the code action on l.1 can be executed with `:lua vim.lsp.buf.code_action()` but Fastaction doesn't propose anything.

**Comment by galou** [comment]
Only one code action available.

**Comment by tsukimizake** [comment]
`vim.lsp.diagnostic.get_line_diagnostic` was returning this.
```lua
{ {
    code = "undefined-global",
    message = "Undefined global `vim`.",
    range = {
      ["end"] = {
        character = 47,
        line = 40
      },
      start = {
        character = 44,
        line = 40
      }
    },
    severity = 2,
    source = "Lua Diagnostics."
  } }
```

and #19 's `vim.diagnostic.get` returns it. 

```lua
 { {
      bufnr = 5,
      code = "undefined-global",
      col = 44,
      end_col = 47,
      end_lnum = 40,
      lnum = 40,
      message = "Undefined global `vim`.",
      namespace = 19,
      severity = 2,
      source = "Lua Diagnostics.",
      user_data = {
        lsp = {
          code = "undefined-global",
          message = "Undefined global `vim`.",
          range = {
            ["end"] = {
              character = 47,
              line = 40
            },
            start = {
              character = 44,
              line = 40
            }
          },
          severity = 2,
          source = "Lua Diagnostics."
        }
      }
    } }
```

I patched fastaction/lsp.lua:41 to reformat the result like the old way, and it's working on me.

```lua
  local diags = vim.diagnostic.get(M.bufnr, { lnum = lnum })

  local diags_in_lsp_get_line_diags_style = {}
  for key, item in pairs(diags) do
    diags_in_lsp_get_line_diags_style[key] = item.user_data.lsp
  end

  local params = vim.lsp.util.make_range_params()
  params.context = { diagnostics = diags_in_lsp_get_line_diags_style }
```

**Comment by mawkler** [comment]
I'm having this exact issue with rust-analyzer (using [rustacenvim](https://github.com/mrcjkb/rustaceanvim)). After some bisecting it seems like the bad commit is 17be938295e715a1b9bfc6ae90adedf4112bf98d.

**Comment by Chaitanyabsprip** [comment]
I'm thinking of removing all the custom code for handling code actions and simply wrapping `vim.lsp.buf.code_action` and `vim.lsp.buf.range_code_action` with `fastaction.Select`. This would simplify the plugin and also make the results consistent.

**Comment by AssisrMatheus** [comment]
> I'm thinking of removing all the custom code for handling code actions and simply wrapping `vim.lsp.buf.code_action` and `vim.lsp.buf.range_code_action` with `fastaction.Select`. This would simplify the plugin and also make the results consistent.

Don't know if related or not but with https://github.com/nvimtools/none-ls.nvim, i'm not able to see actions like `Ignore the lint message` and the like. Maybe by reading off of lsp directly, this will also get fixed!
