### ISSUE TITLE
Make popup window appear under the cursor

### ISSUE THREAD

**Issue by diniamo** [Chaitanyabsprip/fastaction.nvim#5]
I've been at this for a while, but no luck. I saw in the [Reddit post](https://www.reddit.com/r/neovim/s/sRy6fpdcPF), that it's possible, but I didn't see anything extra set for it in [the configuration](https://github.com/Chaitanyabsprip/nvim/blob/152a8fac0210398a07e9808d8090ded26cea4c61/lua/plugins/lsp.lua#L77-L102) used.

This is my setup call currently:
```lua
require("fastaction").setup({
  ["dismiss_keys"] = { "q", "<esc>" },
  ["keys"] = "abcdefghijklmnoprstuvwxyz",
  ["popup"] = { ["relative"] = "cursor", ["title"] = "Select:", ["y_offset"] = 1 },
  ["register_ui_select"] = true,
})
```

But whatever I do, it always opens in the top-right corner.

**Comment by Chaitanyabsprip** [comment]
This was fixed with the latest release. Thanks for creating an issue.

**Comment by Chaitanyabsprip** [comment]
Also the gif in the reddit post demonstrates the code actions popup.
