### ISSUE TITLE
Errors with rust analyzer

### ISSUE THREAD

**Issue by nicflower** [Chaitanyabsprip/fastaction.nvim#9]
I am trying to use the plugin within a rust project ([here](https://github.com/nicflower/dotfiles/tree/main/nvim) my whole config), but I am facing this error:
<img width="1440" alt="immagine" src="https://github.com/user-attachments/assets/52adecfe-6cbf-43cb-b513-f0587334e2f2">

here's an example starting with the creation of a simple hello world project:

https://github.com/user-attachments/assets/445888d8-ba58-4702-886e-bc47cfe16f55

(this is a continuation of a discussion started [here](https://www.reddit.com/r/neovim/comments/1f352y6/comment/lkcb36h/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by Chaitanyabsprip** [comment]
Hey @nicflower, thank you raising the issue. I suspect the issue lies in you configuration. I've tried again to reproduce this following the steps you have shown in the gif. If either you could share a minimal configuration of your nvim with rust support I could help you debug the error.

**Comment by nicflower** [comment]
thanks for the reply @Chaitanyabsprip, I have tried to remove most of my plugins and keep just the one used by the LSP (and then telescope and treesitter basically), I created a separate branch [here](https://github.com/nicflower/dotfiles/tree/debug_fast_actions). If you have time to give it a look it would be really helpful.

**Comment by nicflower** [comment]
I may have found the problem, upgrading to nvim 0.10.1 (previously I was running 0.9.5) solved the issue. Thanks for the support anyway!
